version: '3.8'

services:
  mongo_container:
    image: mongo:6.0 
    container_name: mymongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  python_app:
    build: .
    container_name: python_app
    depends_on:
      - mymongo